info:
  configuration:
    profile: test

eureka:
  client:
    enabled: false

logging:
  level:
    com.learning.meetingrooms: WARN

test:
  message: "Hello from Git Repository - Version 1"
  feature-flag: true
  max-connections: 150