server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh,monitor
  info:
    env:
      enabled: true

info:
  configuration:
    source: git-config-repository

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moatzahmed/microservice-project-configs.git
          clone-on-start: true
          default-label: main 
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

test:
  message: "Hello from Git Repository - Version 1.1"
  feature-flag: true
  max-connections: 150