server:
  port: 8081

spring:
  application:
    name: room-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/new-meeting-room}
  datasource:
    url: ${ROOM_DB_URL:jdbc:postgresql://localhost:5433/room_db}
    username: ${ROOM_DB_USERNAME}
    password: ${ROOM_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  pattern:
    correlation: "[%X{correlationId:-no-correlation}] "